# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            MathBlog
tagline:          'By Pilotman Pirx'
description:      'Blog about mainly Math.'
url:              https://github.com/Pilotman
baseurl:          /MathBlog/

author:
  name:           'Diego Pirx'
  twitter:            https://twitter.com/DiegoPirx
  instagram:       https://www.instagram.com/diego_pirx/

paginate:         5

# Custom vars
version:          0.2.1

github:
  repo:           https://github.com/Pilotman/

# Permalinks
permalink: pretty
relative_permalinks: false

taglist:
  #- algebra
  #- topology
  - English
  - Number Theory
  - Set Theory
  - Series
  - Algebraic Structures
  - Abstract Algebra
  - Español
