# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            MathBlog
tagline:          'By Pilotman Pirx'
description:      'Sobre todo hablo de Mates'
url:              https://github.com/Pilotman
baseurl:          /MathBlog/

author:
  name:           'Diego Pirx'
  twitter:         https://twitter.com/DiegoViverRod/
  instagram:       https://www.instagram.com/diego_pirx/

paginate:         2

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/Pilotman/

# Permalinks
permalink: pretty
relative_permalinks: false

taglist:
  - algebra
  #- topology
  - English
  - Number Theory
  - Set Theory
  - Series
  - Algebraic Structures
  - Abstract Algebra
  - Español
  - No mates
  - Non maths
  - Updates
  - Python

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
